import type { Metadata } from "next";
import "./styles/globals.css";
import Head from "next/head";

export const metadata: Metadata = {
  title: "ВИДЕОХРАНИТЕЛЬ Кемерово",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      </Head>
      <body>
        {children}
      </body>
    </html>
  );
}
